version = 1

test_patterns = [
  "tests/**",
  "test_*.py"
]

exclude_patterns = [
  "documentation/**",
  "images/**",
  "**/examples/**"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["pyproject.toml"]

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 80
  skip_doc_coverage = ["module", "magic", "init"]
  additional_builtins = ["_", "pretty_output"]
