name: Publish to PyPI
on:
  release:
    types: [published]
jobs:
  build-n-publish:
    name: PyPI - Build and publish Python ðŸ distributions ðŸ“¦
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "install poetry-dynamic-versioning"
        run:
          pip install poetry-dynamic-versioning
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.2
        with:
          python_version: "3.6"
          poetry_version: ">=0.12"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
