name: Publish Python ðŸ distributions ðŸ“¦ to PyPI
on: push
jobs:

  build-n-publish:
    name: PyPI - Build and publish Python ðŸ distributions ðŸ“¦
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@master
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.1
        with:
          python_version: '3.6'
          poetry_version: '>=0.12'
          pypi_token: ${{ secrets.PYPI_TOKEN }}

  build-n-publish-test-pypi:
    name: Test PyPI - Build and publish Python ðŸ distributions ðŸ“¦
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@master
      - name: Build and publish to test pypi
        uses: JRubics/poetry-publish@v1.1
        with:
          python_version: '3.6'
          poetry_version: '>=0.12'
          pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_name: 'testpypi'
          repository_url: 'https://test.pypi.org/legacy/'
